name: ibslibenv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - alabaster==0.7.12
      - appdirs==1.4.4
      - argon2-cffi==20.1.0
      - arrow==1.1.0
      - astroid==2.5.6
      - async-generator==1.10
      - atomicwrites==1.4.0
      - attrs==21.2.0
      - babel==2.9.1
      - backcall==0.2.0
      - beautifulsoup4==4.9.3
      - binaryornot==0.4.4
      - black==21.6b0
      - bleach==3.3.0
      - breathe==4.30.0
      - cachecontrol==0.12.6
      - cachy==0.3.0
      - cffi==1.14.5
      - chardet==4.0.0
      - cleo==0.8.1
      - click==7.1.2
      - clikit==0.6.2
      - cookiecutter==1.7.3
      - cpymad==1.8.1
      - crashtest==0.3.1
      - cryptography==3.4.7
      - cycler==0.10.0
      - debugpy==1.3.0
      - decorator==5.0.9
      - defusedxml==0.7.1
      - distlib==0.3.2
      - docutils==0.17.1
      - entrypoints==0.3
      - et-micc==1.1.8
      - et-micc-build==1.1.8
      - filelock==3.0.12
      - html5lib==1.1
      - ibslibpy==0.0.0
      - idna==2.10
      - imagesize==1.2.0
      - importlib-resources==5.2.0
      - ipykernel==6.0.1
      - ipython==7.25.0
      - ipython-genutils==0.2.0
      - isort==5.9.0
      - jedi==0.18.0
      - jeepney==0.6.0
      - jinja2==3.0.1
      - jinja2-time==0.2.0
      - jsonschema==3.2.0
      - jupyter-client==6.2.0
      - jupyter-contrib-core==0.3.3
      - jupyter-contrib-nbextensions==0.5.1
      - jupyter-core==4.7.1
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-latex-envs==1.4.6
      - jupyter-nbextensions-configurator==0.4.1
      - jupyterlab-pygments==0.1.2
      - keyring==21.8.0
      - kiwisolver==1.3.1
      - lazy-object-proxy==1.6.0
      - lockfile==0.12.2
      - lxml==4.6.3
      - markupsafe==2.0.1
      - matplotlib==3.4.2
      - matplotlib-inline==0.1.2
      - mccabe==0.6.1
      - minrpc==0.1.0
      - mistune==0.8.4
      - more-itertools==8.8.0
      - msgpack==1.0.2
      - mypy==0.910
      - mypy-extensions==0.4.3
      - nbclient==0.5.3
      - nbconvert==6.1.0
      - nbformat==5.1.3
      - nbsphinx==0.8.6
      - nest-asyncio==1.5.1
      - notebook==6.4.0
      - numpy==1.21.0
      - packaging==20.9
      - pandas==1.3.0
      - pandoc==1.1.0
      - pandocfilters==1.4.3
      - parso==0.8.2
      - pastel==0.2.1
      - pathspec==0.8.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==8.2.0
      - pkginfo==1.7.0
      - pluggy==0.13.1
      - plumbum==1.7.0
      - ply==3.11
      - poetry==1.1.6
      - poetry-core==1.0.3
      - poyo==0.5.0
      - prometheus-client==0.11.0
      - prompt-toolkit==3.0.19
      - ptyprocess==0.7.0
      - py==1.10.0
      - pybind11==2.6.2
      - pycparser==2.20
      - pygments==2.9.0
      - pylev==1.4.0
      - pylint==2.8.3
      - pyparsing==2.4.7
      - pypi-simple==0.8.0
      - pyrsistent==0.18.0
      - pytest==4.6.11
      - python-dateutil==2.8.1
      - python-slugify==5.0.2
      - pytz==2021.1
      - pyyaml==5.4.1
      - pyzmq==22.1.0
      - regex==2021.4.4
      - requests==2.25.1
      - requests-toolbelt==0.9.1
      - rstcheck==3.3.1
      - secretstorage==3.3.1
      - semantic-version==2.8.5
      - send2trash==1.7.1
      - setuptools-cpp==0.1.0
      - shellingham==1.4.0
      - six==1.16.0
      - snowballstemmer==2.1.0
      - soupsieve==2.2.1
      - sphinx==3.5.3
      - sphinx-click==2.7.1
      - sphinx-rtd-theme==0.4.3
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - terminado==0.10.1
      - testpath==0.5.0
      - text-unidecode==1.3
      - toml==0.10.2
      - tomlkit==0.5.11
      - tornado==6.1
      - traitlets==5.0.5
      - typing-extensions==3.10.0.0
      - urllib3==1.26.5
      - virtualenv==20.4.7
      - walkdir==0.4.1
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - wrapt==1.12.1
      - zipp==3.4.1
